/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as LabelsRouteImport } from './routes/labels'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TasksProjectIdRouteImport } from './routes/tasks/$projectId'

const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const LabelsRoute = LabelsRouteImport.update({
  id: '/labels',
  path: '/labels',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksProjectIdRoute = TasksProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => TasksRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/labels': typeof LabelsRoute
  '/reports': typeof ReportsRoute
  '/tasks': typeof TasksRouteWithChildren
  '/timeline': typeof TimelineRoute
  '/tasks/$projectId': typeof TasksProjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/labels': typeof LabelsRoute
  '/reports': typeof ReportsRoute
  '/tasks': typeof TasksRouteWithChildren
  '/timeline': typeof TimelineRoute
  '/tasks/$projectId': typeof TasksProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/labels': typeof LabelsRoute
  '/reports': typeof ReportsRoute
  '/tasks': typeof TasksRouteWithChildren
  '/timeline': typeof TimelineRoute
  '/tasks/$projectId': typeof TasksProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/labels'
    | '/reports'
    | '/tasks'
    | '/timeline'
    | '/tasks/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/labels'
    | '/reports'
    | '/tasks'
    | '/timeline'
    | '/tasks/$projectId'
  id:
    | '__root__'
    | '/'
    | '/labels'
    | '/reports'
    | '/tasks'
    | '/timeline'
    | '/tasks/$projectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LabelsRoute: typeof LabelsRoute
  ReportsRoute: typeof ReportsRoute
  TasksRoute: typeof TasksRouteWithChildren
  TimelineRoute: typeof TimelineRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labels': {
      id: '/labels'
      path: '/labels'
      fullPath: '/labels'
      preLoaderRoute: typeof LabelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$projectId': {
      id: '/tasks/$projectId'
      path: '/$projectId'
      fullPath: '/tasks/$projectId'
      preLoaderRoute: typeof TasksProjectIdRouteImport
      parentRoute: typeof TasksRoute
    }
  }
}

interface TasksRouteChildren {
  TasksProjectIdRoute: typeof TasksProjectIdRoute
}

const TasksRouteChildren: TasksRouteChildren = {
  TasksProjectIdRoute: TasksProjectIdRoute,
}

const TasksRouteWithChildren = TasksRoute._addFileChildren(TasksRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LabelsRoute: LabelsRoute,
  ReportsRoute: ReportsRoute,
  TasksRoute: TasksRouteWithChildren,
  TimelineRoute: TimelineRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
