name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

permissions:
  contents: read
  pull-requests: write

# Skip duplicate jobs on PRs
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: ./tooling/github/setup

      - name: Prettier Check
        run: pnpm format

      - name: Build
        run: pnpm build

      - name: Type Check
        run: pnpm typecheck

      - name: ESLint Check
        run: pnpm lint
